CREATE TABLE user (
    id INT DEFAULT NULL AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE session (
    id INT DEFAULT NULL AUTO_INCREMENT PRIMARY KEY,
    hash VARCHAR(1000) NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id)
);